name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python-image

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pythonaddimage
      - name: View Docker Images
        run: docker images
      - name: Run Docker Container
        run: docker run pythonaddimage
      - name: Delete Docker Image
        run: |
          echo "Deleting Docker Image"
          docker rm pythonaddimage
